Carpooling/Models/TravelViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Carpooling.Models
{
    public class TravelViewModel
    {
        [RegularExpression(@"^[A-Z][a-z]*$", ErrorMessage = "City name must start with a capital letter and be followed by lowercase letters.")]
        public string CityStartDest { get; set; }
        [RegularExpression(@"^[A-Z][a-z]*$", ErrorMessage = "City name must start with a capital letter and be followed by lowercase letters.")]
        public string CityEndDest { get; set; }
        [RegularExpression(@"^([A-Z][a-z]*(\s[A-Z][a-z]*)*)$", ErrorMessage = "Invalid country name format.")]
        public string Country { get; set; }
        [Display(Name = "Departure Time")]
        [DateTimeNotInPast]
        [DataType(DataType.DateTime)]
        public DateTime DepartureTime { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Available Seats must be a non-negative number.")]
        public int AvailableSeats { get; set; }
        [RegularExpression(@"^[A-ZА-Я0-9]+$", ErrorMessage = "Registration must contain only uppercase letters.")]
        public string CarRegistration { get; set; }
    }
}

Carpooling/Controllers/FeedbackController.cs
using AutoMapper;
using Carpooling.BusinessLayer.Exceptions;
using Carpooling.BusinessLayer.Services;
using CarPooling.Data.Exceptions;
using CarPooling.Data.Models;
using Carpooling.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Carpooling.BusinessLayer.Services.Contracts;
using CarPooling.Data.Data;
using Microsoft.EntityFrameworkCore;
using Carpooling.Service.Dto_s.Responses;

namespace Carpooling.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly IUserService userService;
        private readonly IFeedbackService feedbackService;
        private readonly UserManager<User> userManager;
        private readonly ITravelService travelService;
        public FeedbackController(UserManager<User> userManager, IFeedbackService feedbackService, IUserService userService, ITravelService travelService)
        {
            this.userManager = userManager;
            this.feedbackService = feedbackService;
            this.userService = userService;
            this.travelService = travelService;
        }


        [HttpGet]
        public async Task<IActionResult> Create(string participantId, int travelId)
        {
            var feedbackModel = new FeedbackViewModel();
            feedbackModel.ParticipantId = participantId;
            feedbackModel.TravelId = travelId;


            return View(feedbackModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(FeedbackViewModel feedbackModel, string participantId, int travelId)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Challenge();
            }
            if (!this.ModelState.IsValid)
            {
                return this.View(feedbackModel);
            }
            try
            {
                var user = await userManager.Users.Include(c => c.Cars)
                  .SingleAsync(x => x.UserName.Equals(User.Identity.Name));

                var travel = await travelService.GetTravelAsync(travelId);
                var participant = await this.userService.GetUserByIdAsync(participantId);

                var feedback = new Feedback
                {
                    Rating = feedbackModel.Rating,
                    Comment = feedbackModel.Comment,
                    ReceiverId = participant.Id,
                    GiverId = user.Id,
                    TravelId = travelId
                };

                var feedbackGiver = await userManager.FindByIdAsync(user.Id);
                _ = await this.feedbackService.CreateAsync(feedback, feedbackGiver);

                return RedirectToAction("MyTravels", "Travels");
            }
            catch (UnauthorizedOperationException ex)
            {
                HttpContext.Response.StatusCode = StatusCodes.Status403Forbidden;
                this.ViewData["ErrorMessage"] = ex.Message;
                return View("Error");
            }
            catch (EntityUnauthorizatedException ex)
            {
                HttpContext.Response.StatusCode = StatusCodes.Status403Forbidden;
                this.ViewData["ErrorMessage"] = ex.Message;
                return View("Error");
            }
            catch (EntityNotFoundException ex)
            {
                HttpContext.Response.StatusCode = StatusCodes.Status404NotFound;
                this.ViewData["ErrorMessage"] = ex.Message;
                return View("Error");
            }

        }
    }
}

Carpooling/Controllers/PersonalController.cs
using AutoMapper;
using Carpooling.BusinessLayer.Exceptions;
using Carpooling.BusinessLayer.Services;
using Carpooling.BusinessLayer.Services.Contracts;
using Carpooling.BusinessLayer.Validation;
using Carpooling.Models;
using Carpooling.Service.Dto_s.Responses;
using CarPooling.Data.Data;
using CarPooling.Data.Exceptions;
using CarPooling.Data.Models;
using CarPooling.Data.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

namespace Carpooling.Controllers
{
    public class PersonalController : Controller
    {
        private readonly IUserService userService;
        private readonly ICarService carService;
        private readonly IFeedbackService feedbackService;
        //private readonly ITripRequestService tripRequestService;
        private readonly UserManager<User> userManager;

        public PersonalController(IUserService userService, ICarService carService, IFeedbackService feedbackService, UserManager<User> userManager)
        {
            this.userService = userService;
            this.carService = carService;
            this.feedbackService = feedbackService;
            this.userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> DriverInfo([FromRoute] string id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Challenge();
            }
            if (id == null)
            {
                var user1 = await userManager.GetUserAsync(User);
                id = user1.Id;
            }
            var cars = await carService.GetAllAsync();
            var feedbacks = await feedbackService.GetAllAsync();
            var driverFeedbacks = feedbacks.Where(x => x.ReceiverId == id);
            var feedbacksAsPassenger = feedbacks.Where(x=>x.GiverId == id);

            var user = await userManager.Users.Include(c => c.Cars)
                   .SingleAsync(x => x.Id.Equals(id));

            var driverCars = user.Cars;


            var driverModel = new DriverViewInfoModel
            {
                Username = user.UserName,
                AverageRating = user.AverageRating,
                ReceivedFeedbacks = driverFeedbacks,
                GivenFeedbacks = feedbacksAsPassenger,
                Cars = driverCars
            };

            return View(driverModel);
        }

        [HttpGet]
        public async Task<IActionResult> PassengerInfo([FromRoute] string id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Challenge();
            }
            if (id == null)
            {
                var user1 = await userManager.GetUserAsync(User);
                id = user1.Id;
            }
            var user = await userService.GetByIdAsync(id);
            var feedbacks = await feedbackService.GetAllAsync();
            var passengerFeedbacks = feedbacks.Where(x => x.ReceiverId == id);
            
          //  var currentUser = new User();

            var passengerModel = new PassengerViewInfoModel
            {
                
                Username = user.Username,
                AverageRating = user.AverageRating,
                Feedbacks = passengerFeedbacks

            };

            return View(passengerModel);
        }

        [HttpGet]
        public async Task<IActionResult> Menu()
        {
            return View("~/Views/Shared/_MenuPartial.cshtml");
        }

        //[HttpGet]
        //public async Task<IActionResult> CreateCar()
        //{
        //    if (!User.Identity.IsAuthenticated)
        //    {
        //        return Challenge();
        //    }
        //    var carViewModel = new CarViewModel();
        //    return View(carViewModel);
        //}

        //[HttpPost]
        //public async Task<IActionResult> CreateCar(CarViewModel carViewModel)
        //{
        //    if (!User.Identity.IsAuthenticated)
        //    {
        //        return Challenge();
        //    }
        //    if (!this.ModelState.IsValid)
        //    {
        //        return this.View(carViewModel);
        //    }
        //    try
        //    {

        //        var user = await userManager.Users.Include(c => c.Cars)
        //            .SingleAsync(x => x.UserName.Equals(User.Identity.Name));
        //        var car = mapper.Map<Car>(carViewModel);
        //        var createdCar = await carService.CreateAsync(car, user);
        //        return this.RedirectToAction("DriverInfo", "Personal", new { id = user.Id });
        //    }
        //    catch (UnauthorizedOperationException ex)
        //    {
        //        HttpContext.Response.StatusCode = StatusCodes.Status403Forbidden;
        //        this.ViewData["ErrorMessage"] = ex.Message;
        //        return View("Error");
        //    }
        //    catch (DublicateEntityException ex)
        //    {
        //        HttpContext.Response.StatusCode = StatusCodes.Status403Forbidden;
        //        this.ViewData["ErrorMessage"] = ex.Message;
        //        return View("Error");
        //    }
        //}

        
        //[HttpGet]
        //public async Task<IActionResult> MyCars()
        //{
        //    try
        //    {
        //        if (!User.Identity.IsAuthenticated)
        //        {
        //            return Challenge();
        //        }
        //        var user = await userManager.Users.Include(x => x.Cars)
        //               .SingleAsync(x => x.UserName.Equals(User.Identity.Name));
        //        var carHistory = user.Cars;
        //        var cars = new List<Car>();
        //        foreach (var car in carHistory)
        //        {
        //            var car1 = await this.carService.GetByIdAsync(car.Id);
        //            if (car.IsDeleted == false)
        //            {
        //                cars.Add(car1);
        //            }
        //        }
        //        return this.View(cars);
        //    }
        //    catch (EntityNotFoundException ex)
        //    {
        //        HttpContext.Response.StatusCode = StatusCodes.Status404NotFound;
        //        this.ViewData["ErrorMessage"] = ex.Message;
        //        return View("Error");
        //    }
        //}
    }
}

Carpooling/Views/Travels/Create.cshtml
@using Carpooling.Models
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims
@using CarPooling.Data.Models;
@inject UserManager<User> UserManager
@model TravelViewModel
@{
    ViewData["Title"] = "Create";
}

@{
    await Html.RenderPartialAsync("_MenuPartial");
}

@{
    var user = await UserManager.GetUserAsync(User);
}


<div><br></div>
@if (user.IsBlocked == true)
{
    <h1>You have been blocked and you do not have permission to create a travel.</h1>
}
<h2>Create Travel</h2>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <p><strong>Validation Error:</strong> Please correct the errors and try again.</p>
    </div>
}

<form asp-controller="Travels" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="CityStartDest">Start Location for City</label>
        <input asp-for="CityStartDest" class="form-control" />
        <span asp-validation-for="CityStartDest" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CityEndDest">End Location for City</label>
        <input asp-for="CityEndDest" class="form-control" />
        <span asp-validation-for="CityEndDest" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DepartureTime">Departure Time</label>
        <input asp-for="DepartureTime" class="form-control" />
        <span asp-validation-for="DepartureTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="AvailableSeats">Available Seats</label>
        <input asp-for="AvailableSeats" class="form-control" />
        <span asp-validation-for="AvailableSeats" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CarRegistration">Car Registration</label>
        <input asp-for="CarRegistration" class="form-control" />
        <span asp-validation-for="CarRegistration" class="text-danger"></span>
    </div>
    </br>
    </br>
    @if (user.IsBlocked == true)
    {
        <p></p>
    }
    else
    {
        <button type="submit" class="btn btn-primary">Create Travel</button>
    }
    <a asp-action="Menu" asp-controller="Personal" class="btn btn-secondary">Back</a>
</form>


        

Carpooling/Views/Travels/Details.cshtml
@using CarPooling.Data.Models;
@using Carpooling.Models;
@using Carpooling.Service.Dto_s.Responses;
@using Microsoft.AspNetCore.Identity;
@inject UserManager<User> UserManager
@{
    this.ViewData["Title"] = "Details";
    var user = await UserManager.GetUserAsync(User);
}
@model TravelResponse


<div class="travel-container">
    <h2>Travel Details</h2>
    <br>
    <p><i class="fas fa-map-marker-alt"></i> <span class="property">Start Location:</span> @Model.StartLocationName</p>
    <p><i class="fas fa-flag"></i> <span class="property">Destination:</span> @Model.DestinationName</p>
    <p><i class="fas fa-calendar"></i> <span class="property">Departure Time:</span> @Model.DepartureTime.ToString("yyyy-MM-dd HH:mm")</p>
    <p><i class="fas fa-clock"></i> <span class="property">Estimated Time Of Arrival:</span> @Model.ArrivalTime.ToString("yyyy-MM-dd HH:mm")</p>
    <p><i class="fas fa-chair"></i> <span class="property">Available Seats:</span> @Model.AvailableSeats</p>
    <p><i class="fas fa-check-circle"></i> <span class="property">Is Complete:</span> @(Model.IsCompleted ? "Yes" : "No")</p>
    <p><i class="fas fa-car"></i> <span class="property">Car Registration:</span> @Model.CarRegistration</p>
    <p><i class="fas fa-car"></i> <span class="property">Distance Between Destinations In Kms:</span> @Model.DistanceBetweenDestinations KM</p>
</div>
</br>
@if (User.Identity.IsAuthenticated)
{
    <div class="create-request-button" style="text-align: left;">
        @if (this.Model.IsCompleted == true || this.Model.ArrivalTime < DateTime.Now)
        {
            <p>Organised travel has already happened.</p>
        }
        else
        {
            @if (user.IsBlocked == true)
            {
                <h3>You have been blocked! You cannot create trip requests!</h3>
            }
            else
            {
                @if (this.Model.AvailableSeats > 0)
                {
                    <a asp-controller="TripRequest" asp-action="CreateTripRequest" asp-route-id="@this.ViewBag.id" class="btn btn-success">Create Trip Request</a>
                }
                else
                {
                    <p>Unfortunately there are no available seats :(</p>
                }
            }
        }
        <a asp-controller="Travels" asp-action="Index" class="btn btn-success">Go Back</a>
    </div>
}







@*<div class="travel-container">
    <h2>Travel Details</h2>
    <p><span class="property">Start Location:</span> @Model.StartLocationName</p>
    <p><span class="property">Destination:</span> @Model.DestinationName</p>
    <p><span class="property">Departure Time:</span> @Model.DepartureTime.ToString("yyyy-MM-dd HH:mm")</p>
    <p><span class="property">Arrival Time:</span> @Model.ArrivalTime.ToString("yyyy-MM-dd HH:mm")</p>
    <p><span class="property">Available Seats:</span> @Model.AvailableSeats</p>
    <p><span class="property">Is Complete:</span> @(Model.IsComplete ? "Yes" : "No")</p>
    <p><span class="property">Car Registration:</span> @Model.CarRegistration</p>
</div>*@

Carpooling/Views/Travels/Index.cshtml
@using CarPooling.Data.Models.Pagination;
@using CarPooling.Data.Models;
@using Carpooling.PaginationHelper;
@using Carpooling.Service.Dto_s.Responses;

@{
    this.ViewData["Title"] = "Travels";
    Pager pager = new Pager();

    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
    
}

@model IEnumerable<Travel>
<form asp-controller="Travels" asp-action="Index" method="get">
    <div class="input-group mb-3">
        <input type="text" name="searchQuery" class="form-control" placeholder="Search by Start Location, End Location, or UserName." />
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit">Search</button>
        </div>
    </div>
    @if (User.IsInRole("Administrator"))
    {
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="sortBySelect">Sort By</label>
            </div>
            <select class="custom-select" id="sortBySelect" name="sortBy">
                <option value="id" selected="@(ViewBag.SortBy == "id")">Default</option>
                <option value="startlocation" selected="@(ViewBag.SortBy == "startlocation")">Start Location</option>
                <option value="endlocation" selected="@(ViewBag.SortBy == "endlocation")">End Location</option>
                <option value="departuretime" selected="@(ViewBag.SortBy == "departuretime")">Departure Time</option>
                <option value="arrivaltime" selected="@(ViewBag.SortBy == "arrivaltime")">Arrival Time</option>
            </select>
            <input type="hidden" name="sortBy" value = "@ViewBag.SortBy" />
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Apply</button>
            </div>
        </div>
    }
</form>
@if (!Model.Any())
{
    <br>
    <h3 class="no-results">No results</h3>
}
else
{
    <div class="travel-list">
        <div class="travel-item header">
            <div class="start-end-locations">
                <div class="label">Start/</div>
                <div class="label">End Location</div>
            </div>
            <div class="label" style="text-align: center;">Departure Time</div>
            <div class="label" style="text-align: right;">Arrival Time</div>   
            <div class="label" style="text-align: right;">Driver</div>
        </div>
        @foreach (var travel in Model)
        {
            <a class="travel-item" href="@Url.Action("Details", "Travels", new { id = travel.Id })">
                <div class="start-end-locations">
                    <div class="location">@travel.StartLocation.City</div>
                    <div class="divider">-</div>
                    <div class="location">@travel.EndLocation.City</div>
                </div>
                <div class="departure-time" style="text-align: center;">@travel.DepartureTime</div>
                <div class="arrival-time" style="text-align: right;">@travel.ArrivalTime</div>      
                <div class="driver" style="text-align: right;">@travel.Driver?.UserName</div>
            </a>
        }
    </div>
    <div class="container">
        @if (pager.TotalPages > 0)
        {    
            <ul class="pagination justify-content-end">
                @if (pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Travels" asp-action="Index" asp-route-pg="1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Travels" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">Previous</a>
                    </li>
                }
                @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                {
                    <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-controller="Travels" asp-action="Index" asp-route-pg="@pge" asp-route-sortBy="@ViewBag.SortBy">@pge</a>
                    </li>
                }
                @if (pager.CurrentPage < pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Travels" asp-action="Index" asp-route-pg="@(pager.CurrentPage+1)">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Travels" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                    </li>
                }
            </ul>
        }
    </div>
}

Carpooling/Views/Travels/MyTravels.cshtml
@inject UserManager<User> UserManager;
@using CarPooling.Data.Models;
@using Carpooling.Models;
@using Microsoft.AspNetCore.Identity;
@model List<TravelViewResponseWithId>

@{
    ViewData["Title"] = "My Travels";
}

@{
    await Html.RenderPartialAsync("_MenuPartial");
}

@{
    var loggedUser = await UserManager.GetUserAsync(User);
}

<br>
@if (Model is null || Model.Count() == 0)
{

    <h3> You currently have no trips yet.  </h3>

}
else
{
    @if (!Model.Any(t => !t.IsCompleted))
    {
        <br>
        <h3> At the moment, you still have no incomplete travels. </h3>
        <br>
        <br>
        <hr>
    }
    else
    {

        <h2>My Travel(s):</h2>
        <br>
        <div>
            <h3>Incomplete Travels:</h3>
            @foreach (var travel in @Model.Where(t => !t.IsCompleted))
            {
                <div class="travel-container">
                    <h2>Travel Details</h2>
                    <br>
                    <p><i class="fas fa-map-marker-alt"></i> <span class="property">Start city:</span> @travel.StartLocationName</p>
                    <p><i class="fas fa-flag"></i> <span class="property">Destination city:</span> @travel.DestinationName</p>
                    <p><i class="fas fa-calendar"></i> <span class="property">Departure Time:</span> @travel.DepartureTime</p>
                    <p><i class="fas fa-clock"></i> <span class="property">Arrival Time:</span> @travel.ArrivalTime</p>
                    <p><i class="fas fa-chair"></i> <span class="property">Available Seats:</span> @travel.AvailableSeats</p>
                    <p><i class="fas fa-check-circle"></i> <span class="property">Is Complete:</span> @(travel.IsCompleted ? "Yes" : "No")</p>
                    <p><i class="fas fa-car"></i> <span class="property">Car Registration:</span> @travel.CarRegistration</p>
                    @if (loggedUser.TravelHistory.Count() != 0)
                    {
                        <div>
                            <form asp-controller="Travels" asp-action="SetComplete" method="post">
                                <input type="hidden" name="travelId" value="@travel.Id">
                                <button type="submit" name="complete" value="complete">Мark as complete</button>
                            </form>
                        </div>
                        <div>
                            <form asp-controller="Travels" asp-action="DeleteTravel" method="post">
                                <input type="hidden" name="travelId" value="@travel.Id">
                                <button type="submit" name="delete" value="delete">Cancel a trip</button>
                            </form>
                            <br>
                        </div>
                    }
                </div>
                <br>
            }
        </div>
    }
    <br>
    <br>
    @if (!Model.Any(t => t.IsCompleted))
    {
        <br>
        <h3> At the moment, you still have no completed travels. </h3>
    }
    else
    {

        <div>
            <h3>Complete Travels:</h3>
            @foreach (var travel in @Model.Where(t => t.IsCompleted))
            {
                <div class="travel-container">
                    <h2>Travel Details</h2>
                    <br>
                    <p><i class="fas fa-map-marker-alt"></i> <span class="property">Start city:</span> @travel.StartLocationName</p>
                    <p><i class="fas fa-flag"></i> <span class="property">Destination city:</span> @travel.DestinationName</p>
                    <p><i class="fas fa-calendar"></i> <span class="property">Departure Time:</span> @travel.DepartureTime</p>
                    <p><i class="fas fa-clock"></i> <span class="property">Arrival Time:</span> @travel.ArrivalTime</p>
                    <p><i class="fas fa-chair"></i> <span class="property">Available Seats:</span> @travel.AvailableSeats</p>
                    <p><i class="fas fa-check-circle"></i> <span class="property">Is Complete:</span> @(travel.IsCompleted ? "Yes" : "No")</p>
                    <p><i class="fas fa-car"></i> <span class="property">Car Registration:</span> @travel.CarRegistration</p>
                    <br>
                    <div class="participants-container">
                        <h5>Participant(s):</h5>
                        <br>
                        @if (travel.DriverId.Equals(loggedUser.Id))
                        {

                            @foreach (var participant in travel.Participants)
                            {
                                var isLeftFeedbackForUserFeedbacks = false;

                                <div class="participant">
                                    <p><i class="fas fa-user"></i> <span class="property">Participant:</span> @participant.UserName</p>
                                    @foreach (var feedback in participant.ReceivedFeedbacks)
                                    {
                                        if (feedback.TravelId == travel.Id)
                                        {
                                            isLeftFeedbackForUserFeedbacks = true;
                                            break;
                                        }
                                    }

                                    @if (!isLeftFeedbackForUserFeedbacks)
                                    {
                                        <form asp-controller="Feedback" asp-action="Create" method="get">
                                            <input type="hidden" name="ParticipantId" value="@participant.Id">
                                            <input type="hidden" name="TravelId" value="@travel.Id">
                                            <button type="submit" class="submit-button">Leave Feedback</button>
                                        </form>
                                    }
                                </div>
                                <br>
                            }
                        }
                        else
                        {
                            var isLeftFeedbackForUser = false;
                            var driver = await UserManager.FindByIdAsync(travel.DriverId);
                            <div class="participant">
                                <p><i class="fas fa-user"></i> <span class="property">Driver:</span> @driver.UserName</p>
                                @foreach (var feedback in driver.ReceivedFeedbacks)
                                {
                                    if (feedback.TravelId == travel.Id)
                                    {
                                        isLeftFeedbackForUser = true;
                                        break;
                                    }
                                }
                                @if (!isLeftFeedbackForUser)
                                {
                                    <form asp-controller="Feedback" asp-action="Create" method="get">
                                        <input type="hidden" name="ParticipantId" value="@driver.Id">
                                        <input type="hidden" name="TravelId" value="@travel.Id">
                                        <button type="submit" class="submit-button">Leave Feedback</button>
                                    </form>
                                }
                            </div>
                        }
                    </div>
                </div>
                <br>
            }
        </div>
    }
}
<br>
<a asp-action="Menu" asp-controller="Personal" class="btn btn-secondary">Go Back</a>