Carpooling/Models/CarViewModel.cs
using System.ComponentModel.DataAnnotations;
using Carpooling.AttributeHelpers;
namespace Carpooling.Models
{
    public class CarViewModel
    {
        [RegularExpression(@"^[A-ZА-Я0-9]+$", ErrorMessage = "Registration must contain only uppercase letters.")]
        public string Registration { get; set; }
        public int TotalSeats { get; set; }
        [AvailableSeatsAttribute("TotalSeats", ErrorMessage = "Available seats cannot be greater than total seats.")]
        public int AvailableSeats { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        [RegularExpression(@"^[A-Z][a-z]*$", ErrorMessage = "Color must start with a capital letter and be followed by lowercase letters.")]
        public string Color { get; set; }
        public bool CanSmoke { get; set; }
    }
}

Carpooling/Controllers/CarController.cs
using AutoMapper;
using Carpooling.BusinessLayer.Exceptions;
using Carpooling.BusinessLayer.Services;
using CarPooling.Data.Exceptions;
using CarPooling.Data.Models;
using Carpooling.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Carpooling.BusinessLayer.Services.Contracts;
using Microsoft.EntityFrameworkCore;

namespace Carpooling.Controllers
{
    public class CarController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly ICarService carService;
        private readonly IMapper mapper;

        public CarController(UserManager<User> userManager, ICarService carService, IMapper mapper)
        {
            this.userManager = userManager;
            this.carService = carService;
            this.mapper = mapper;

        }
        [HttpGet]
        public async Task<IActionResult> CreateCar()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Challenge();
            }
            var carViewModel = new CarViewModel();
            return View(carViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateCar(CarViewModel carViewModel)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Challenge();
            }
            if (!this.ModelState.IsValid)
            {
                return this.View(carViewModel);
            }
            try
            {

                var user = await userManager.Users.Include(c => c.Cars)
                    .SingleAsync(x => x.UserName.Equals(User.Identity.Name));
                var car = mapper.Map<Car>(carViewModel);
                var createdCar = await carService.CreateAsync(car, user);
                return this.RedirectToAction("DriverInfo", "Personal", new { id = user.Id });
            }
            catch (UnauthorizedOperationException ex)
            {
                HttpContext.Response.StatusCode = StatusCodes.Status403Forbidden;
                this.ViewData["ErrorMessage"] = ex.Message;
                return View("Error");
            }
            catch (DuplicateEntityException ex)
            {
                HttpContext.Response.StatusCode = StatusCodes.Status403Forbidden;
                this.ViewData["ErrorMessage"] = ex.Message;
                return View("Error");
            }
            
        }


        [HttpGet]
        public async Task<IActionResult> MyCars()
        {
            try
            {
                if (!User.Identity.IsAuthenticated)
                {
                    return Challenge();
                }
                var user = await userManager.Users.Include(x => x.Cars)
                       .SingleAsync(x => x.UserName.Equals(User.Identity.Name));
                var carHistory = user.Cars;
                var cars = new List<Car>();
                foreach (var car in carHistory)
                {
                    var car1 = await this.carService.GetByIdAsync(car.Id);
                    if (car.IsDeleted == false)
                    {
                        cars.Add(car1);
                    }
                }
                return this.View(cars);
            }
            catch (EntityNotFoundException ex)
            {
                HttpContext.Response.StatusCode = StatusCodes.Status404NotFound;
                this.ViewData["ErrorMessage"] = ex.Message;
                return View("Error");
            }
        }
    }
}

Carpooling/Views/Car/CreateCar.cshtml
@using CarPooling.Data.Models;
@using Carpooling.Models
@using Microsoft.AspNetCore.Identity;
@inject UserManager<User> UserManager
@model CarViewModel

@{
    ViewData["Title"] = "Create Car";
}

@{
    await Html.RenderPartialAsync("_MenuPartial");
}

@{
    var user = await UserManager.GetUserAsync(User);
}

<div><br></div>
@if (user.IsBlocked == true)
{
    <h1>You have been blocked and you do not have permission to create a travel.</h1>
}
<h2>@ViewData["Title"]</h2>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <h4>Please correct the following errors:</h4>
        <ul>
            @foreach (var key in ViewData.ModelState.Keys)
            {
                foreach (var error in ViewData.ModelState[key].Errors)
                {
                    <li>@error.ErrorMessage</li>
                }
            }
        </ul>
    </div>
}

<form asp-controller="Car" asp-action="CreateCar" method="post">
    <div class="form-group">
        <label asp-for="Registration" class="control-label"></label>
        <input asp-for="Registration" class="form-control" />
        <span asp-validation-for="Registration" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TotalSeats" class="control-label"></label>
        <input asp-for="TotalSeats" class="form-control" />
        <span asp-validation-for="TotalSeats" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="AvailableSeats" class="control-label"></label>
        <input asp-for="AvailableSeats" class="form-control" />
        <span asp-validation-for="AvailableSeats" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Brand" class="control-label"></label>
        <input asp-for="Brand" class="form-control" />
        <span asp-validation-for="Brand" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Model" class="control-label"></label>
        <input asp-for="Model" class="form-control" />
        <span asp-validation-for="Model" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Color" class="control-label"></label>
        <input asp-for="Color" class="form-control" />
        <span asp-validation-for="Color" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CanSmoke" class="control-label"></label>
        <input asp-for="CanSmoke" class="form-check-input" type="checkbox" />
        <span asp-validation-for="CanSmoke" class="text-danger"></span>
    </div>
    </br>
    @if (user.IsBlocked == true)
    {
        <p></p>
    }
    else
    {
        <button type="submit" class="btn btn-primary">Create Car</button>
    }
    <a asp-action="Menu" asp-controller="Personal" class="btn btn-secondary">Back</a>
</form>

Carpooling/Views/Car/MyCars.cshtml
@using CarPooling.Data.Models
@model List<Car>

@{
    ViewData["Title"] = "My Vehicles";
}

@{
    await Html.RenderPartialAsync("_MenuPartial");
}


<br>
@if (Model.Count == 0)
{
    <h3>You have no cars registered.</h3>
}
else
{
    <h2>My Cars</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Registration</th>
                <th>Total Seats</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Color</th>
                <th>Can Smoke</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var car in Model)
            {
                <tr>
                    <td>@car.Registration</td>
                    <td>@car.TotalSeats</td>
                    <td>@car.Brand</td>
                    <td>@car.Model</td>
                    <td>@car.Color</td>
                    <td>@(car.CanSmoke ? "Yes" : "No")</td>
                </tr>
            }
        </tbody>
    </table>
}
<br>
<a asp-action="Menu" asp-controller="Personal" class="btn btn-secondary">Go Back</a>